### PR TITLE
adding support for 9216 (RTD) module

### PR DESCRIPTION
**Pull request by dbendele**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-module-libraries/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add support for 9216 module

### Why should this Pull Request be merged?

SEECD does not currently support 9216 (RTD measurements)

### What testing has been done?

SEECD deploys with VS 2017 (with the 9216 module added to system definition) correctly
The 9216 settings were changed to exercise all options of device-specific config. 
Deploy and test successful to Linux64 target (9045).

### CODE REVIEW

**Comment by dbendele** [comment]
The diff pictures are nice, but you may want to refer to the 9217 class VIs as a basis for comparison. The 9217 is a 4-channel RTD module that served as the starting point for the _new_ VIs.

**Comment by rtzoeller** [comment]
## 9216.lvclass:Initialize.vi
- [ ] Help me validate my understanding: where do these constants come from?
- [ ] They seem to be duplicated in `Default Channel Configuration.vi`, we should single source them.

image

## 9216.lvclass:Configure Module.vi

- [ ] The class controls have a weird name (likely left over from many copy-pastes, most recently from the 9217 class). Name them to be consistent with the other VIs.

image


- [ ] No action required, I just really like this approach compared to how it is done in the 9217.

image

**Comment by dbendele** [comment]
those constants are scaling coefficients for RTD of type TCR 8351. It is a reasonable starting point should the user change the RTD type to custom. The user would get the coefficients for their custom RTD from the sensor datasheet or more recent calibration.

**Comment by dbendele** [comment]
The constant values should definitely be single sourced!

**Pull request merged**
