### PR TITLE
Remove Pharlap and Linux ARM support

### PR DESCRIPTION
**Pull request by Karl-G1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-module-libraries/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Copies implementation from #41. #41 can then be closed, and 2021 support will be added later.

- Remove PXI Pharlap and Linux ARM build specs
- Convert existing PXI target to Linux x64 for cRIO and PXI support
- Add Windows build specification

### Why should this Pull Request be merged?

Prepare for 21.0 and 64-bit library support

### What testing has been done?

None

### CODE REVIEW

**Comment by rtzoeller** [comment]
@Karl-G1 I believe we need to convert the removed Pharlap build spec to a Windows one.

**Comment by Karl-G1** [comment]
@rtzoeller Ready for another look. I fixed the Linux x64 build specs (they still had Pharlap build paths) and added similar Windows build specs for both components.

**Review by rtzoeller — APPROVED** [review]

**Comment by rtzoeller** [comment]
Approved because the changes are conceptually good, but I'd like you to validate SEECD can be built for Linux and Windows with these changes. I saw an issue locally.

**Comment by Karl-G1** [comment]
> Approved because the changes are conceptually good, but I'd like you to validate SEECD can be built for Linux and Windows with these changes. I saw an issue locally.

As we saw on the phone earlier, https://github.com/ni/niveristand-scan-engine-module-libraries/pull/43/commits/ca9f514ed9cff965c2eebc7bee770f3dc5193b61 fixes the Linux build issue. This is good to merge, but I am waiting on https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/169 to go in first, otherwise it will not have the full module support to build the PR.

**Pull request merged**
