### PR TITLE
Add Support for 9210, 9226, 9253 Modules

### PR DESCRIPTION
**Pull request by dbendele**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-module-libraries/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds support for the 9210, 9226, 9253.

### Why should this Pull Request be merged?

These modules are not currently supported, and this should add support for these requested modules.

### What testing has been done?

These changes were built locally for pharlap and Linux 64 targets in LV 2017 and LV 2019. 
9226 configuration pages were exercised in VS 2017.
9210, 9226, 9253 configuration pages exercised in VS 2019.
Unit tests run and passed.

### CODE REVIEW

**Comment by dbendele** [comment]
This request depends on https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/79

**Comment by rtzoeller** [comment]
Which classes were copied to add these new ones?

**Comment by dbendele** [comment]
> Which classes were copied to add these new ones?
9216 copied and modified for 9226
9214 copied and modified for 9210  
9203 copied and modified for 9253

**Comment by rtzoeller** [comment]
- [ ] The filter frequencies for the 9253 are coupled together in the UI; whenever one is updated, the other is updated as well. Since they're not the same length, this causes issues when the last butterworth frequency is selected and then the filter response is switched to comb.



I'd prefer if we just used two fields in the class data to store these values independently, and selected between them in `Configure Module.vi` based on which filter response is selected.

**Comment by rtzoeller** [comment]
- [ ] The active selection for the 9210 MCL gets reset to the first element when changing the thermocouple type or measurement units. This makes it annoying to change both the thermocouple type and measurement units for a channel other than the first.

**Comment by dbendele** [comment]
> * [ ]  The filter frequencies for the 9253 are coupled together in the UI; whenever one is updated, the other is updated as well. Since they're not the same length, this causes issues when the last butterworth frequency is selected and then the filter response is switched to comb.

> I'd prefer if we just used two fields in the class data to store these values independently, and selected between them in `Configure Module.vi` based on which filter response is selected.

Yes, they are coupled. This was done to reflect that the device only supports one filter configuration frequency when configuring the hardware in Configure Module VI. This custom device isn't designed to support _switching_ between one valid Butterworth filter configuration and another valid comb filter configuration. My expectation is that the user would select the appropriate filter for their application. Since comb with filter frequency = 5 is invalid, would you consider alternative that configuration coerce the  comb filter frequency to nearest valid value (4: Filter Frequency = Fs / 16)?

**Comment by rtzoeller** [comment]
I would either be fine coercing the value, or storing them independently.

My preference for storing them independently was that if a user had configured a butterworth filter, and then inadvertently switched to comb, they would be put back in their original configuration if they switched back to butterworth. The System Explorer doesn't have an undo button, so the user can't just hit that.

**Pull request merged**
